sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t ajeshkumars/docker-react .

script:
  - docker run -e CI=true ajeshkumars/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-322729342396"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
